import type { Route } from "next";

import { Suspense } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";

import {
  DataTable,
  DataTableBody,
  DataTableCell,
  DataTableHead,
  DataTableHeader,
  DataTableRow,
} from "@/components/dashboard/data-table";
import { PageHeader } from "@/components/dashboard/page-header";
import { ReportGenerateForm } from "@/components/reports/report-generate-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyTitle,
} from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { requireSession } from "@/lib/auth/session";
import { getClientById } from "@/lib/services/client.service";
import { getReportsByClient } from "@/lib/services/report.service";

interface ClientReportsPageProps {
  params: Promise<{ clientId: string }>;
}

export default function ClientReportsPage({ params }: ClientReportsPageProps) {
  return (
    <Suspense fallback={<ClientReportsSkeleton />}>
      <ClientReports params={params} />
    </Suspense>
  );
}

async function ClientReports({ params }: ClientReportsPageProps) {
  await requireSession();
  const { clientId } = await params;
  const [client, reports] = await Promise.all([
    getClientById(clientId).catch(() => null),
    getReportsByClient(clientId),
  ]);

  if (!client) {
    notFound();
  }

  const defaultPeriod = getPreviousMonthPeriod();

  return (
    <>
      <PageHeader
        actions={
          <Button
            render={<Link href={`/clients/${client.id}` as Route} />}
            variant="outline"
          >
            Back to client
          </Button>
        }
        description="Generate internal monthly summaries from stored ranking and GSC performance snapshots. Rerunning the same period refreshes the existing report."
        eyebrow="Reports"
        title={`${client.name} reports`}
      />

      <Card className="bg-card/95">
        <CardHeader>
          <CardTitle>Generate monthly report</CardTitle>
        </CardHeader>
        <CardContent>
          <ReportGenerateForm
            clientId={client.id}
            defaultPeriodEnd={defaultPeriod.end}
            defaultPeriodStart={defaultPeriod.start}
          />
        </CardContent>
      </Card>

      <Card className="bg-card/95">
        <CardHeader>
          <CardTitle>{reports.length} generated reports</CardTitle>
        </CardHeader>
        <CardContent>
          {reports.length > 0 ? (
            <DataTable>
              <DataTableHeader>
                <DataTableRow>
                  <DataTableHead>Period</DataTableHead>
                  <DataTableHead>Status</DataTableHead>
                  <DataTableHead>Generated</DataTableHead>
                  <DataTableHead>Generated by</DataTableHead>
                  <DataTableHead>Action</DataTableHead>
                </DataTableRow>
              </DataTableHeader>
              <DataTableBody>
                {reports.map((report) => (
                  <DataTableRow key={report.id}>
                    <DataTableCell>
                      {formatDate(report.periodStart)} –{" "}
                      {formatDate(report.periodEnd)}
                    </DataTableCell>
                    <DataTableCell>
                      <Badge variant="secondary">{report.status}</Badge>
                    </DataTableCell>
                    <DataTableCell>
                      {formatDate(report.createdAt)}
                    </DataTableCell>
                    <DataTableCell>
                      {report.generatedBy ?? "Unknown"}
                    </DataTableCell>
                    <DataTableCell>
                      <Button
                        render={
                          <Link
                            href={
                              `/clients/${client.id}/reports/${report.id}` as Route
                            }
                          />
                        }
                        size="sm"
                        variant="outline"
                      >
                        Open
                      </Button>
                    </DataTableCell>
                  </DataTableRow>
                ))}
              </DataTableBody>
            </DataTable>
          ) : (
            <Empty className="border">
              <EmptyHeader>
                <EmptyTitle>No reports generated</EmptyTitle>
                <EmptyDescription>
                  Generate last month&apos;s report once this client has synced
                  ranking snapshots.
                </EmptyDescription>
              </EmptyHeader>
            </Empty>
          )}
        </CardContent>
      </Card>
    </>
  );
}

function ClientReportsSkeleton() {
  return (
    <>
      <Skeleton className="h-24 w-full" />
      <Skeleton className="h-44 w-full" />
      <Skeleton className="h-72 w-full" />
    </>
  );
}

function getPreviousMonthPeriod() {
  const now = new Date();
  const start = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1)
  );
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 0));

  return {
    start: toDateInput(start),
    end: toDateInput(end),
  };
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeZone: "UTC",
  }).format(date);
}

function toDateInput(date: Date) {
  return date.toISOString().slice(0, 10);
}
